##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.6.0.1-B1] date: [Sat Jun 14 17:31:37 CST 2025]
##########################################################################################################################

# ------------------------------------------------
# STM32 firmware Makefile
#
# The root Makefile keeps the final build graph in one place. Module files only
# append sources, include paths, and local switches.
# ------------------------------------------------

ROOT := $(shell pwd)
TARGET := STM32-freertos
BUILD_DIR := build

include mk/config.mk
include mk/common.mk

include Core/module.mk
include Drivers/module.mk
include Middlewares/module.mk

include mk/rules.mk

# *** EOF ***
