#ifndef PARTITION_CONFIG_H
#define PARTITION_CONFIG_H

#include "platform_config.h"

/*
 * STM32F103xE Flash map.
 *
 * This header is the only compile-time source of partition addresses.
 * Later partitions start at the previous END, so changing a SIZE shifts
 * everything after it. Keep every SIZE a multiple of the erase page.
 *
 * Flash: 0x08000000 - 0x08080000, 512KB
 *
 * 0x08000000  Stage0                 16KB
 * 0x08004000  PartitionTable_0        4KB
 * 0x08005000  PartitionTable_1        4KB
 * 0x08006000  BootControl_0           4KB
 * 0x08007000  BootControl_1           4KB
 * 0x08008000  Bootloader_A           48KB
 * 0x08014000  Bootloader_B           48KB
 * 0x08020000  App_A                 160KB
 * 0x08048000  App_B                 160KB
 * 0x08070000  Config                 64KB
 * 0x08080000
 */

#define PARTITION_KB(n) ((n) * 1024u)

#define PARTITION_FLASH_BASE_ADDR    PLATFORM_FLASH_BASE_ADDR
#define PARTITION_FLASH_SIZE         PLATFORM_FLASH_SIZE
#define PARTITION_FLASH_END_ADDR     (PLATFORM_FLASH_BASE_ADDR + PLATFORM_FLASH_SIZE)
#define PARTITION_FLASH_ERASE_SIZE   PLATFORM_FLASH_ERASE_SIZE

#define PARTITION_STAGE0_ADDR        PARTITION_FLASH_BASE_ADDR
#define PARTITION_STAGE0_SIZE        PARTITION_KB(16)
#define PARTITION_STAGE0_END_ADDR    (PARTITION_STAGE0_ADDR + PARTITION_STAGE0_SIZE)

#define PARTITION_PARTITION_TABLE_0_ADDR     PARTITION_STAGE0_END_ADDR
#define PARTITION_PARTITION_TABLE_0_SIZE     PARTITION_KB(4)
#define PARTITION_PARTITION_TABLE_0_END_ADDR (PARTITION_PARTITION_TABLE_0_ADDR + PARTITION_PARTITION_TABLE_0_SIZE)

#define PARTITION_PARTITION_TABLE_1_ADDR     PARTITION_PARTITION_TABLE_0_END_ADDR
#define PARTITION_PARTITION_TABLE_1_SIZE     PARTITION_KB(4)
#define PARTITION_PARTITION_TABLE_1_END_ADDR (PARTITION_PARTITION_TABLE_1_ADDR + PARTITION_PARTITION_TABLE_1_SIZE)

#define PARTITION_BOOTCTRL_0_ADDR        PARTITION_PARTITION_TABLE_1_END_ADDR
#define PARTITION_BOOTCTRL_0_SIZE        PARTITION_KB(4)
#define PARTITION_BOOTCTRL_0_END_ADDR    (PARTITION_BOOTCTRL_0_ADDR + PARTITION_BOOTCTRL_0_SIZE)

#define PARTITION_BOOTCTRL_1_ADDR        PARTITION_BOOTCTRL_0_END_ADDR
#define PARTITION_BOOTCTRL_1_SIZE        PARTITION_KB(4)
#define PARTITION_BOOTCTRL_1_END_ADDR    (PARTITION_BOOTCTRL_1_ADDR + PARTITION_BOOTCTRL_1_SIZE)

#define PARTITION_BOOT_A_ADDR        PARTITION_BOOTCTRL_1_END_ADDR
#define PARTITION_BOOT_A_SIZE        PARTITION_KB(48)
#define PARTITION_BOOT_A_END_ADDR    (PARTITION_BOOT_A_ADDR + PARTITION_BOOT_A_SIZE)

#define PARTITION_BOOT_B_ADDR        PARTITION_BOOT_A_END_ADDR
#define PARTITION_BOOT_B_SIZE        PARTITION_KB(48)
#define PARTITION_BOOT_B_END_ADDR    (PARTITION_BOOT_B_ADDR + PARTITION_BOOT_B_SIZE)

#define PARTITION_APP_A_ADDR         PARTITION_BOOT_B_END_ADDR
#define PARTITION_APP_A_SIZE         PARTITION_KB(160)
#define PARTITION_APP_A_END_ADDR     (PARTITION_APP_A_ADDR + PARTITION_APP_A_SIZE)

#define PARTITION_APP_B_ADDR         PARTITION_APP_A_END_ADDR
#define PARTITION_APP_B_SIZE         PARTITION_KB(160)
#define PARTITION_APP_B_END_ADDR     (PARTITION_APP_B_ADDR + PARTITION_APP_B_SIZE)

#define PARTITION_CONFIG_ADDR        PARTITION_APP_B_END_ADDR
#define PARTITION_CONFIG_SIZE        PARTITION_KB(64)
#define PARTITION_CONFIG_END_ADDR    (PARTITION_CONFIG_ADDR + PARTITION_CONFIG_SIZE)

#define CONFIG_PART_ADDR             PARTITION_CONFIG_ADDR
#define CONFIG_PART_SIZE             PARTITION_CONFIG_SIZE

#define PARTITION_ASSERT_ALIGNED(tag, addr, size)                                      \
    _Static_assert(((addr) % PARTITION_FLASH_ERASE_SIZE) == 0u,                        \
                   tag " address is not erase aligned");                               \
    _Static_assert(((size) % PARTITION_FLASH_ERASE_SIZE) == 0u,                        \
                   tag " size is not erase aligned")

#define PARTITION_ASSERT_CONTIGUOUS(tag, addr, size, next_addr)                        \
    _Static_assert(((addr) + (size)) == (next_addr),                                   \
                   tag " is not contiguous with the next partition")

PARTITION_ASSERT_ALIGNED("stage0", PARTITION_STAGE0_ADDR, PARTITION_STAGE0_SIZE);
PARTITION_ASSERT_ALIGNED("partition_table_0", PARTITION_PARTITION_TABLE_0_ADDR, PARTITION_PARTITION_TABLE_0_SIZE);
PARTITION_ASSERT_ALIGNED("partition_table_1", PARTITION_PARTITION_TABLE_1_ADDR, PARTITION_PARTITION_TABLE_1_SIZE);
PARTITION_ASSERT_ALIGNED("bootctrl_0", PARTITION_BOOTCTRL_0_ADDR, PARTITION_BOOTCTRL_0_SIZE);
PARTITION_ASSERT_ALIGNED("bootctrl_1", PARTITION_BOOTCTRL_1_ADDR, PARTITION_BOOTCTRL_1_SIZE);
PARTITION_ASSERT_ALIGNED("boot_a", PARTITION_BOOT_A_ADDR, PARTITION_BOOT_A_SIZE);
PARTITION_ASSERT_ALIGNED("boot_b", PARTITION_BOOT_B_ADDR, PARTITION_BOOT_B_SIZE);
PARTITION_ASSERT_ALIGNED("app_a", PARTITION_APP_A_ADDR, PARTITION_APP_A_SIZE);
PARTITION_ASSERT_ALIGNED("app_b", PARTITION_APP_B_ADDR, PARTITION_APP_B_SIZE);
PARTITION_ASSERT_ALIGNED("config", PARTITION_CONFIG_ADDR, PARTITION_CONFIG_SIZE);

PARTITION_ASSERT_CONTIGUOUS("stage0", PARTITION_STAGE0_ADDR, PARTITION_STAGE0_SIZE, PARTITION_PARTITION_TABLE_0_ADDR);
PARTITION_ASSERT_CONTIGUOUS("partition_table_0", PARTITION_PARTITION_TABLE_0_ADDR, PARTITION_PARTITION_TABLE_0_SIZE, PARTITION_PARTITION_TABLE_1_ADDR);
PARTITION_ASSERT_CONTIGUOUS("partition_table_1", PARTITION_PARTITION_TABLE_1_ADDR, PARTITION_PARTITION_TABLE_1_SIZE, PARTITION_BOOTCTRL_0_ADDR);
PARTITION_ASSERT_CONTIGUOUS("bootctrl_0", PARTITION_BOOTCTRL_0_ADDR, PARTITION_BOOTCTRL_0_SIZE, PARTITION_BOOTCTRL_1_ADDR);
PARTITION_ASSERT_CONTIGUOUS("bootctrl_1", PARTITION_BOOTCTRL_1_ADDR, PARTITION_BOOTCTRL_1_SIZE, PARTITION_BOOT_A_ADDR);
PARTITION_ASSERT_CONTIGUOUS("boot_a", PARTITION_BOOT_A_ADDR, PARTITION_BOOT_A_SIZE, PARTITION_BOOT_B_ADDR);
PARTITION_ASSERT_CONTIGUOUS("boot_b", PARTITION_BOOT_B_ADDR, PARTITION_BOOT_B_SIZE, PARTITION_APP_A_ADDR);
PARTITION_ASSERT_CONTIGUOUS("app_a", PARTITION_APP_A_ADDR, PARTITION_APP_A_SIZE, PARTITION_APP_B_ADDR);
PARTITION_ASSERT_CONTIGUOUS("app_b", PARTITION_APP_B_ADDR, PARTITION_APP_B_SIZE, PARTITION_CONFIG_ADDR);
PARTITION_ASSERT_CONTIGUOUS("config", PARTITION_CONFIG_ADDR, PARTITION_CONFIG_SIZE, PARTITION_FLASH_END_ADDR);

_Static_assert(PARTITION_STAGE0_ADDR == PARTITION_FLASH_BASE_ADDR,
               "stage0 must start at the MCU reset vector");
_Static_assert(PARTITION_CONFIG_END_ADDR == PARTITION_FLASH_END_ADDR,
               "partition layout must end at the flash end");

#endif /* PARTITION_CONFIG_H */
